apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-bom
spec:
  params:
    - name: ibmcloud-apikey-secret-key
      description: field in the secret that contains the api key used to login to ibmcloud
      default: apikey
    - name: continuous-delivery-context-secret
      description: Reference name for the secret resource
      default: "secure-properties"
    - name: TOOLCHAIN_ID
      description: the workspace id
  workspaces:
    - name: artifacts
      mountPath: /artifacts
  steps:
    - name: bom-cli-test
      image: davidlopez0912/test-plugin:v1
      env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.continuous-delivery-context-secret)
              key: $(params.ibmcloud-apikey-secret-key)
              optional: true
        - name: TOOLCHAIN_ID
          value: $(params.TOOLCHAIN_ID)
      command: ["/bin/bash", "-c"]
      args:
        - |
          #!/bin/bash

          export TOOLCHAIN_ID=$TOOLCHAIN_ID
          REGION="--us-south"
          ibmcloud login --apikey $API_KEY -a "https://test.cloud.ibm.com" -r us-south

          ibmcloud plugin install /tmp/cli-cra-plugin/doi-cli-linux-amd64-0.3.2

          ibmcloud cra bom-generate --dir /tmp/cli-cra-plugin --report /tmp/test.json

  sidecars:
    - image: docker:19.03-dind
      name: server
      securityContext:
        privileged: true
      env:
        # enable BUILDKIT Option
        - name: DOCKER_BUILDKIT
          value: 1
        # Write generated certs to the path shared with the client.
        - name: DOCKER_TLS_CERTDIR
          value: /certs
      volumeMounts:
        - mountPath: /var/run/
          name: docker-socket
      # Wait for the dind daemon to generate the certs it will share with the client.
      readinessProbe:
        periodSeconds: 1
        exec:
          command: ["ls", "/certs/client/ca.pem"]

  volumes:
    - name: config-volume
      configMap:
        name: toolchain
    - name: docker-socket
      emptyDir: {}
    - name: environment-properties
      configMap:
        name: $(params.continuous-delivery-context-environment)
    - name: secure-properties
      secret:
        secretName: $(params.continuous-delivery-context-secret)
    - name: retry-script
      configMap:
        name: retry-script
        items:
          - key: retry.sh
            path: retry.sh
