apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-bom
spec:
  params:
    - name: ibmcloud-apikey-secret-key
      description: field in the secret that contains the api key used to login to ibmcloud
      default: apikey
    - name: continuous-delivery-context-secret
      description: Reference name for the secret resource
      default: "secure-properties"
    - name: TOOLCHAIN_ID
      description: the workspace id
  workspaces:
    - name: artifacts
      mountPath: /artifacts
  steps:
    - name: bom-cli-test
      image: davidlopez0912/test-plugin:v1
      env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.continuous-delivery-context-secret)
              key: $(params.ibmcloud-apikey-secret-key)
              optional: true
        - name: TOOLCHAIN_ID
          value: $(params.TOOLCHAIN_ID)
        # Docker config
        - name: DOCKER_HOST
          value: "tcp://localhost:2376"
        - name: DOCKER_TLS_VERIFY
          value: "1"
        - name: DOCKER_CERT_PATH
          value: /certs/client
        - name: DOCKER_CONFIG
          value: /steps
      command: ["/bin/bash", "-c"]
      args:
        - |
          #!/bin/bash

          docker info

          export TOOLCHAIN_ID=$TOOLCHAIN_ID
          REGION="--us-south"
          ibmcloud login --apikey $API_KEY -a "https://test.cloud.ibm.com" -r us-south

          ibmcloud plugin install /tmp/cli-cra-plugin/doi-cli-linux-amd64-0.3.2

          ibmcloud cra bom-generate --dir /tmp/cli-cra-plugin --report /tmp/test.json
      volumeMounts:
        - mountPath: /steps
          name: steps-volume
        - mountPath: /certs/client
          name: dind-certs
  sidecars:
    - image: docker:19.03.14-dind
      name: server
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: /certs
      volumeMounts:
        - mountPath: /certs/client
          name: dind-certs
      readinessProbe:
        periodSeconds: 1
        exec:
          command: ["ls", "/certs/client/ca.pem"]
  volumes:
    - name: steps-volume
      emptyDir: {}
    - name: dind-certs
      emptyDir: {}
